### PR TITLE
Add: unit tests, test-utils file for MobX, and Jest reconfiguration

### PR DESCRIPTION
**Pull request by vimwitch**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe):
- This PR adds unit tests for the loadingButton, loadingCover, Feed, and AppRouter components. 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Additional unit tests added and specified above.
- ```test-utils.tsx``` file was added to add a wrapper around all the tests because MobX requires a Provider around components that are using a store (this is still being worked on so you will see comments in this file for now).
- Reconfigured Jest to ignore any .ico files and added the "preset" option. 
- Added two more testing scripts for "watch" functionality and code coverage. Code coverage will be reconfigured when more tests are written. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vimwitch** [comment]
We're also going to make some major changes to the stores and contexts in the next couple days. Most of that logic is moved into the `@unirep/core` package. We'll also bring the prover implementation into this codebase so you can stub that much more easily during testing.

**Comment by vimwitch** [comment]
Ah yea i see. In the test the error is coming from the `ffjavascript` package. They use a `web-worker` package for cross platform workers. [This](https://github.com/developit/web-worker/blob/master/browser.js) is what the import looks like.

I'd look for some solutions for web worker support inside jest tests. You shouldn't need to create a custom render context. All of our contexts self initialize like [here](https://github.com/Unirep/Unirep-Social/blob/main/packages/frontend/src/context/Synchronizer.ts#L738).

**Comment by vimwitch** [comment]
So I'm thinking more about these contexts. The nice thing about contexts is you should be able to override them by wrapping the target component in `<Context provider={custom stuff} />`. I _think_ you should be able to stub these contexts by doing something like this:

```js
import UserContext from 'context/User'

<UserContext provider={custom provider}>
  <TargetComponent />
</UserContext>
```

This should override the default value. The problem is you'll still have to deal with the imports on the first line, which will reference the `Worker`. I think our contexts implementation makes component testing difficult :/

**Comment by vimwitch** [comment]
Yea you can delete the router file, or if there is a directive to skip the test that's fine too.

**Comment by AnthonyMadia** [comment]
I don't think it's the specific implementation of context but moreso using MobX for state management. I will figure something out :)  
Also, using  ```test.skip()``` should work to override the failing test.

**Comment by vimwitch** [comment]
Ah, remember to remove the debug statements in a future pr.

**Pull request merged**
