### PR TITLE
feat: disable self voting

### PR DESCRIPTION
**Pull request by kittybest**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- disable vote button while the or comment belongs to the user self
- add `padStart('0')` to epoch_key while converting data to prevent wrong determination

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vivianjeng — CHANGES_REQUESTED** [review]

**Comment by AnthonyMadia** [comment]
I think the e2e tests are failing only on the CI and not locally. Have been debugging this but still not sure why and curious if the tests are passing locally for you guys @vimwitch @kittybest

**Comment by vimwitch** [comment]
E2E tests are passing for me locally.

**Comment by kittybest** [comment]
failed for me, paste the error below:
> 1) Landing Page
       "before each" hook for "loads the burger menu on click":
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Failed to fetch

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Landing Page`
      at Data.eval (webpack://@unirep-social/frontend/./src/context/Post.ts?:260:23)
      at Generator.next (<anonymous>)
      at fulfilled (webpack://@unirep-social/frontend/./src/context/Post.ts?:51:24)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     21 seconds                                                                       │
  │ Spec Ran:     landing.cy.ts                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/zhanyuzhen/Documents/Unirep/Unirep-Social/packages/frontend/cypress/scree     (1280x720)
     nshots/landing.cy.ts/Landing Page -- loads the burger menu on click -- before ea               
     ch hook (failed).png                                                                           


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  login.cy.ts                                                                     (2 of 3)


  sign up, log out, then sign in
    ✓ should login without encryption (38858ms)
    1) should login with encryption


  1 passing (1m)
  1 failing

  1) sign up, log out, then sign in
       should login with encryption:
     CypressError: A request callback passed to `cy.intercept()` timed out after returning a Promise that took more than the `defaultCommandTimeout` of `20000ms` to resolve.

If the request callback is expected to take longer than `20000ms`, increase the configured `defaultCommandTimeout` value.

Route: {
  "url": "http://testurl.invalidtld/api/signup?*"
}

Intercepted request: {
  "headers": {
    "host": "testurl.invalidtld",
    "proxy-connection": "keep-alive",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/10.7.0 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36",
    "accept": "*/*",
    "origin": "http://localhost:3000",
    "referer": "http://localhost:3000/",
    "accept-encoding": "gzip, deflate",
    "accept-language": "zh-TW"
  },
  "url": "http://testurl.invalidtld/api/signup?commitment=3004b2339cdd8da6a40dc31ccd85b291e3c22578972205740ab550f2f9d331d8&epk=1ab9df87&signupCode=test_signup_code",
  "method": "GET",
  "httpVersion": "1.1",
  "body": "",
  "responseTimeout": 30000
}

https://on.cypress.io/intercept

**Comment by kittybest** [comment]
@AnthonyMadia I think it works

**Review by AnthonyMadia — APPROVED** [review]
@kittybest Yes, I was patiently waiting to see if they would pass here haha. LGTM

**Pull request merged**
