### PR TITLE
feat: unify backend epoch keys to base-10, and display in base-16 in …

### PR DESCRIPTION
**Pull request by kittybest**
…frontend

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`yarn build`) was run locally and any changes were pushed
- [x] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- frontend will display epoch key in pure base-16 string (instead of base-10, 0x+base-16)
- frontend will send epoch key to backend in base-10 string (: `vote` function)
- backend will store epoch key in base-10 string

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vimwitch — APPROVED** [review]
Good change

**Comment by kittybest** [comment]
That's weird, I ran `test:e2e` locally, it passed, but on circleci it sometimes fails
@vimwitch how do you think?

**Comment by vimwitch** [comment]
Yea we need to do a larger rework to store everything in base 10, then format in base 16 for frontend display

**Comment by kittybest** [comment]
so do you think we could merge now?

**Comment by vimwitch** [comment]
Yea I think so

**Pull request merged**
